version: "2.1"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    volumes: 
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"

  kibana:
    image: kibana:7.3.1
    environment:
      SERVER_NAME: change.this.to.your.host
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  fluent-bit:
    image: fluent/fluent-bit:1.2.2
    volumes:
      - ./config/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - elasticsearch
    ports:
      - "514:514/udp"
#    network_mode: "host"
